import { Backlink } from '@/actions/backlink';

export const mockBacklinks: Backlink[] = [
  {
    id: 'rec1',
    targetUrl: '/blog/seo-strategy-2024',
    sourceDomain: 'searchenginejournal.com',
    domainRating: 86,
    linkType: 'Guest Post',
    status: 'Live',
    dateAcquired: '2024-03-15',
    anchorText: 'effective SEO strategy',
    secondaryAnchorText: 'SEO planning',
    pageUrl: 'https://searchenginejournal.com/expert-seo-strategies/123456/',
    pageTraffic: 15000,
    monthlyDomainTraffic: 2500000,
    cost: 750,
    paymentStatus: 'Paid',
    personResponsible: 'John Smith',
    notes: 'Featured article with custom graphics',
    month: 'March'
  },
  {
    id: 'rec2',
    targetUrl: '/services/technical-seo',
    sourceDomain: 'moz.com',
    domainRating: 92,
    linkType: 'Resource Link',
    status: 'Pending',
    dateAcquired: 'Scheduled for April',
    anchorText: 'technical SEO services',
    secondaryAnchorText: 'SEO technical audit',
    pageUrl: 'https://moz.com/resources/technical-seo-guide',
    pageTraffic: 22000,
    monthlyDomainTraffic: 3800000,
    cost: 0,
    paymentStatus: 'Free',
    personResponsible: 'Sarah Johnson',
    notes: 'Included in their resource directory - no cost',
    month: 'April'
  },
  {
    id: 'rec3',
    targetUrl: '/case-studies/ecommerce-seo',
    sourceDomain: 'semrush.com',
    domainRating: 89,
    linkType: 'Mention',
    status: 'Live',
    dateAcquired: '2024-02-28',
    anchorText: 'ecommerce SEO case study',
    secondaryAnchorText: 'ecommerce optimization',
    pageUrl: 'https://semrush.com/blog/ecommerce-success-stories',
    pageTraffic: 18500,
    monthlyDomainTraffic: 4200000,
    cost: 1200,
    paymentStatus: 'Paid',
    personResponsible: 'Emily Chen',
    notes: 'Included in their roundup of success stories',
    month: 'February'
  },
  {
    id: 'rec4',
    targetUrl: '/blog/local-seo-guide',
    sourceDomain: 'ahrefs.com',
    domainRating: 90,
    linkType: 'Resource Link',
    status: 'Live',
    dateAcquired: '2024-03-10',
    anchorText: 'comprehensive local SEO guide',
    secondaryAnchorText: 'local search optimization',
    pageUrl: 'https://ahrefs.com/blog/local-seo-resources',
    pageTraffic: 25000,
    monthlyDomainTraffic: 3500000,
    cost: 950,
    paymentStatus: 'Paid',
    personResponsible: 'Michael Rodriguez',
    notes: 'Listed as a top resource for local SEO',
    month: 'March'
  },
  {
    id: 'rec5',
    targetUrl: '/services/content-marketing',
    sourceDomain: 'contentmarketinginstitute.com',
    domainRating: 82,
    linkType: 'Guest Post',
    status: 'Pending',
    dateAcquired: 'Scheduled for April',
    anchorText: 'content marketing services',
    secondaryAnchorText: 'content strategy',
    pageUrl: 'https://contentmarketinginstitute.com/articles/seo-content-synergy',
    pageTraffic: 12000,
    monthlyDomainTraffic: 950000,
    cost: 800,
    paymentStatus: 'Invoice Sent',
    personResponsible: 'Jennifer Lopez',
    notes: 'Guest post about SEO and content marketing synergy',
    month: 'April'
  }
];
